### ISSUE TITLE
Can't use keymap functions

### ISSUE THREAD

**Issue by lucax88x** [tjdevries/astronauta.nvim#1]
After installing the plugin and calling your simple example in the readme, I get the following error

attempt to index field 'keymap' (a nil value)

Do I need to manually source the keymap part?

**Comment by Mte90** [comment]
I have the same error.
Reading the readme seems that require to put in a specific file to be executed after the loading of the plugin

**Comment by Mte90** [comment]
I got it with:
```
package.path = package.path .. ";/home/mte90/.vim/plugged/astronauta.nvim/lua/astronauta/"
local k = require"astronauta.keymap"
local nnoremap = k.nnoremap
local inoremap = k.inoremap
local vnoremap = k.vnoremap
local map      = k.map
local nmap     = k.nmap
```

**Comment by mnowotnik** [comment]
Simply add `vim.cmd [[runtime plugin/astronauta.vim]]` after plugin loading phase.

**Comment by yujinyuz** [comment]
Idk what `vim.schedule` does under the hood but mine worked when I did this

```lua
-- Load packer.nvim config
require('jyz.plugins')

vim.schedule(function()
  -- LSP configuration
  require('jyz.lsp')
  -- Telescope
  require('jyz.telescope')
end)
```

My lsp config throws the error so I wrapped it in `vim.schedule` and everything seems to work fine

**Comment by Corey-Keller** [comment]
I have found a much simpler solution to be:
`local nnoremap = require('astronauta.keymap').nnoremap`
as the problem lies in getting `vim.keymap` set

**Comment by tjdevries** [comment]
You need to do something like this:

```lua
vim.cmd [[runtime plugin/astronauta.vim]]
```

In your config before you try and use `vim.keymap`. If you do this, then it will load `vim.keymap`.

This happens in the startup sequence, but you may be trying too early to do this. Sorry for the delay

**Comment by tjdevries** [comment]
(I don't think there is anything I can do about this -- my code only gets executed later in the startup sequence)

**Comment by alexzanderr** [comment]
> ```lua
> vim.cmd [[runtime plugin/astronauta.vim]]
> ```

why you dont add this in readme?

**Comment by valorl** [comment]
> > ```lua
> > vim.cmd [[runtime plugin/astronauta.vim]]
> > ```
> 
> why you dont add this in readme?

I'm sure @tjdevries would welcome a PR for that.

**Comment by alexzanderr** [comment]
yeah, @tjdevries writes good plugins, but the documentation for them ... uhh

**Comment by tjdevries** [comment]
You don't *need* to do that to get it to work. You just need to do that to get it to work if you want to use it in your init.lua. Just as any other plugin, if you would put the mappings in `after/` then this plugin would be loaded first. This is described in the help :)

My plugin cannot possibly get sourced _before_ your init.lua. ;)

**Comment by alexzanderr** [comment]
now its something else. you should mention this in the readme

**Comment by tjdevries** [comment]
OK, added note in readme :)

**Comment by alexzanderr** [comment]
great. great plugin btw. i always wondered how would you map a lua function to vim keybinding (without making the function global). thanks TJ
