### ISSUE TITLE
BUG?: `<silent>` mappings don't work

### ISSUE THREAD

**Issue by sandersantema** [tjdevries/astronauta.nvim#4]
I ported the following snippet of vimscript:
```vimscript
tnoremap <silent><ESC><ESC> <C-\><C-n><Cmd>close<CR>
```
To this snippet of lua:
```lua
tnoremap({
  '<silent><ESC><ESC>',
  function()
    vim.api.nvim_win_close(0, {})
  end
})
```
Which doesn't work, the following however does:
```lua
tnoremap({
  '<ESC><ESC>',
  function()
    vim.api.nvim_win_close(0, {})
  end
})
```

It seems therefore that silent doesn't work in mappings or that this is intentional but not yet documented given the (possibly, since it's a merge request in plugin form :)) WIP nature of the plugin.

**Comment by rudotriton** [comment]
If I read the [code](https://github.com/tjdevries/astronauta.nvim/blob/b8ee68edacf285431cda68bca2ccb8abc6f2ee54/lua/astronauta/keymap.lua#L19-L24) correctly, then something like this should do it.

```lua
tnoremap({
  '<ESC><ESC>',
  function()
    vim.api.nvim_win_close(0, {})
  end,
  silent = true
})
```

**Comment by tjdevries** [comment]
Yes, you should use silent as a paremeter, not as part of the map. Thanks @rudotriton :)
