### ISSUE TITLE
unmap?

### ISSUE THREAD

**Issue by alok** [tjdevries/astronauta.nvim#5]
does this plugin have an unmap feature?

**Comment by tjdevries** [comment]
It does not -- actually this is probably something that should be added to neovim core, either with `nvim_remove_keymap` or something like that. I don't thin we have anything in the API to do this currently.

**Comment by tjdevries** [comment]
Created new issue here: https://github.com/neovim/neovim/issues/15334

**Comment by tjdevries** [comment]
Keymaps are no longer provided by the plugin since it was merged into nvim core.
