### ISSUE TITLE
How to add options like `{ expr = true, noremap = true, silent = true, nowait = true }`

### ISSUE THREAD

**Issue by nyngwang** [tjdevries/astronauta.nvim#6]
As title.

**Comment by tjdevries** [comment]
Hi, I just added expr in latest commit, but you can do it like this:

```lua
vim.keymap.nmap {
  "<leader>t",

  function()
    return "<Plug>PlenaryTestFile"
  end,

  expr = true,
}
```

after the plugin has already been loaded

**Comment by nyngwang** [comment]
It will be very helpful for me if you could also update the README.md. Thanks!
